// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
    public const string leaderboard_gilli_danda = "CgkI8ceAsIsREAIQAQ"; // <GPGSID>
    public const string Pack1 = "com_freestylefootball_pack1";
    public const string Pack2 = "com_freestylefootball_pack2";
    public const string pack3 = "com_freestylefootball_pack3";
    public const string Dollar1Thing = "com_freestylefootball_dollar1";
    public const string Dollar2Thing = "com_freestylefootball_dollar2";
    public const string Dollar3Thing = "com_freestylefootball_dollar3";

    public const string removeAds = "com_freestylefootball_removeads";

}

